version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    environment:
      - cluster.name=kyve-airbyte-elasticsearch-poc
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - "9200:9200"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.6.2
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
networks:
  elastic:
    driver: bridge
volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local